export const GET_JOKES_REQUEST = 'GET_JOKES_REQUEST'
export const GET_JOKES_FAILED = 'GET_JOKES_FAILED'
export const GET_JOKES_SUCCESS = 'GET_JOKES_SUCCESS'
export const CLEAR_JOKES = 'CLEAR_SEARCHBAR'